//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afx.Data.MsSql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Afx.Data.MsSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an aggregate collection repository for object of type &apos;{0}&apos;.
        /// </summary>
        internal static string AggregateCollectionRepositoryNotFound {
            get {
                return ResourceManager.GetString("AggregateCollectionRepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an aggregate object repository for object of type &apos;{0}&apos;.
        /// </summary>
        internal static string AggregateObjectRepositoryNotFound {
            get {
                return ResourceManager.GetString("AggregateObjectRepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the type near &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotResolveType {
            get {
                return ResourceManager.GetString("CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;DATEONLY&apos; is only applicable on DateTime properties near &apos;{0}&apos;.
        /// </summary>
        internal static string DateOnlyInvalidType {
            get {
                return ResourceManager.GetString("DateOnlyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;BETWEEN&apos; expects 2 parameters seperated with and &apos;AND&apos; near &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidBetweenParameterCount {
            get {
                return ResourceManager.GetString("InvalidBetweenParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be casted to type &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property for object of type &apos;{0}&apos; near &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidObjectProperty {
            get {
                return ResourceManager.GetString("InvalidObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator near &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is only applicable on String properties near &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidStringType {
            get {
                return ResourceManager.GetString("InvalidStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;WITHIN&apos; expects 2 parameters seperated with and &apos;AND&apos; near &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidWithinParameterCount {
            get {
                return ResourceManager.GetString("InvalidWithinParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an object data converter for object of type &apos;{0}&apos;.
        /// </summary>
        internal static string ObjectDataConverterNotFound {
            get {
                return ResourceManager.GetString("ObjectDataConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; expects a string value.
        /// </summary>
        internal static string OperatorOnlyValidOnStrings {
            get {
                return ResourceManager.GetString("OperatorOnlyValidOnStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has not been provided.
        /// </summary>
        internal static string ParameterNotProvided {
            get {
                return ResourceManager.GetString("ParameterNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository compilation resulted in errors.
        /// </summary>
        internal static string RepositoryCompilationErrors {
            get {
                return ResourceManager.GetString("RepositoryCompilationErrors", resourceCulture);
            }
        }
    }
}
